### ISSUE TITLE
(Feature) Add new settings to validator role

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/deployment-playbooks#14]
Problem:
- some validators don't need ssh access, we need to disable `ssh/22` for them
- some validators don't need p2p port `tcp/30303` open to the internet

Solution:
add variable `allow_ssh`: true/false
if it's true, `ssh/22` is enabled on the security group. the default value is `true`

add variable `allow_p2p`: true/false
if it's true, `tcp/30303` is enabled on a security group. the default values is `true`

**Comment by phahulin** [comment]
Same variables should be added to `owner` (master of ceremony) role

**Comment by phahulin** [comment]
Also, let's add the following variables to other roles. This will allow us to create small test networks without full https support:

* to `bootnode` role: `allow_8545` that enables `8545` port in security group
* to `netstat` role: `allow_3000` that enables `3000` port in security group
* to `explorer` role: `allow_4000` that enables `4000` port in security group (get it back again)

In all roles these variables should be configurable through `group_vars/all`

**Comment by igorbarinov** [comment]
How users will understand what each port responsive for?

**Comment by phahulin** [comment]
@igorbarinov by "new users" you mean new validators in Oracles network or people who want to create their own separate network based on Oracles?
In both cases I suppose they'll have to follow a readme (Validator's readme or MoC's readme). We can also create a wiki just for this repo, explaining how playbooks work without mentioning consesnsus and governance?

**Comment by igorbarinov** [comment]
I'm not only thinking about validators and community but us in future

Magic numbers are good if its common sense, e.g. 22,80,443 etc.
8545 is ok for ethereum people but still confusing when I should have it open or closed 
3000 and 4000 are not good at all because it's very specific to our implementation

I'd like to have more clear descriptions of port names
e.g. not `allow_8545` but `allow_rpc_on_port_8545` or
``` 
# If true, RPC port is open for external connections
allow_rpc: true
```


not `allow_3000` but `allow_netstat_direct`

```
# If true, Netstat is open for external connections on port 3000 without HTTPS
allow_netstat_direct:3000
```

**Comment by phahulin** [comment]
@igorbarinov how about these

* to `bootnode` role: `allow_rpc_on_8545` that enables 8545 port in security group
* to `netstat` role: `allow_http_on_3000` that enables 3000 port in security group
* to `explorer` role: `allow_http_on_4000` that enables 4000 port in security group (get it back again)

Tried to make it short but informative.

**Comment by igorbarinov** [comment]
sounds good
why don't you like to add comments in the code? :)

**Comment by phahulin** [comment]
We can add comments too.
_(also, I've updated my initial comment with new names)_

**Comment by VitalyZnachenok** [comment]
ready
